### ISSUE TITLE
[Upstream] Contour solution for h2c and websocket

### ISSUE THREAD

**Issue by carlisia** [knative-sandbox/net-gateway-api#366] opened 2022-08-10 15:46 UTC
Ref.: https://github.com/projectcontour/contour/pull/4603.

**Comment by dprotaso** [comment] 2023-02-06 19:32
Closing - dupe of https://github.com/knative-sandbox/net-gateway-api/issues/367

**Closed by dprotaso** 2023-02-06 19:32 UTC
